name: CI

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  build:
    name: Bento4 Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        include:
          - os: ubuntu-latest
            CMAKE_OPTIONS: -DCMAKE_BUILD_TYPE=Release
            CMAKE_OUTPUT_SUBDIR: x86_64-unknown-linux
            PYTHON3_COMMAND: python3  
          - os: macos-latest
            CMAKE_OPTIONS: -G Xcode
            CMAKE_OUTPUT_SUBDIR: universal-apple-macosx
            PYTHON3_COMMAND: python3  
          - os: windows-latest
            CMAKE_OPTIONS: -DCMAKE_BUILD_TYPE=Release
            CMAKE_OUTPUT_SUBDIR: x86_64-microsoft-win32
            PYTHON3_COMMAND: py  

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # CMake Build
      - name: Release Build with CMake
        run: |
          mkdir cmakebuild
          cd cmakebuild
          mkdir ${{matrix.CMAKE_OUTPUT_SUBDIR}}
          cd ${{matrix.CMAKE_OUTPUT_SUBDIR}}
          cmake ${{matrix.CMAKE_OPTIONS}} ../..
          cmake --build . --config Release
      # Create SDK
      - name: Create SDK
        run: ${{matrix.PYTHON3_COMMAND}} Scripts/SdkPackager.py
        
      # Upload the SDK
      - name: Upload SDK
        uses: actions/upload-artifact@v3
        with:
          path: SDK/*.zip

      # Release the SDK
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: SDK/*.zip
